In [1]:
#### Jupyter Basic Setting ####
import pandas as pd,numpy as np, os,sys # np,pd,os,sys
import matplotlib.pyplot as plt,seaborn as sns  # 시각화
import warnings; warnings.filterwarnings('ignore')  # 경고 무시
# 다른 directory Module 불러오기위한 Setting 
parent_dir = os.path.dirname(os.getcwd() )
sys.path.append(parent_dir)
from Module.Functions import *
Service.plotSetting("seaborn-v0_8")
## Data dictionary save 
# np.save("../Data/DataDictionary/subway_dict_test.npy",subway_dict_22_23) ## 99.8Mb
# subway_dict_22_23 =np.load("../Data/DataDictionary/subway_dict_test.npy",allow_pickle=True).tolist()
# subway_dict_22_23.keys()

___## OS platform 한글 세팅완료 ## ___

In [2]:
StationInfo_dict = {}
print(parent_dir)
for i in os.listdir(parent_dir):
    # print(i)
    file_order = 0
    if i =='Data':
        print(f"!{i}")
        for idx, filename in enumerate(os.listdir(os.path.join(parent_dir,i))):
            # print(" |-",j)
            if 'StationInfo' in filename:
                file_order += 1
                print(f"{file_order}. -> ",filename)
                key_name=filename.split(".csv")[0]
                # print(key_name)
                StationInfo_dict[f'{key_name}'] = pd.read_csv(os.path.join(parent_dir,i,filename))
print(Service.colored_text("  >> 📌Data folder 에 있는 년도별 Station Info 를  StationInfo_dict 에 저장합니다.", 'blue'))
print("[[StationInfo keys]]")
for i in StationInfo_dict.keys():
    print("  |-",Service.colored_text(i,'cyan'))

data_name = 'StationInfo_23_0'
print(Service.colored_text(f"✅ {data_name} :역사정보 \n",'yellow'),StationInfo_dict[data_name].head(3))
latlng = pd.read_csv("../Data/seoul_subway_latlon_zenzen.csv")
latlng.rename( {'고유역번호(외부역코드)':'역사코드'}, inplace=True, axis=1)
latlng.drop(['역명','호선','환승역수'], axis=1,inplace=True)
print(Service.colored_text(f"✅ {data_name} : 역사별 위도경도 : \n",'yellow'),latlng.head(3))

## 위도 경도 데이터 merge 
StationInfo_dict[data_name] = pd.merge(StationInfo_dict[data_name],latlng, on='역사코드',how='inner' )
print(Service.colored_text('✅ Merged data check(tail)','yellow'))
print(StationInfo_dict[data_name].tail(3))

# 호선별 배차시간데이터 
savefilename_indexName = data_name.split('StationInfo')[-1]
line_배치_dict ={}
for i in range(1,9):
    line_배치_dict[f'{i}호선'] = pd.read_csv(f'../Data/지하철배차시간데이터/StationInfo{savefilename_indexName}_{i}_호선배차.csv')
    line_배치_dict[f'{i}호선'] = \
        Service.table_merge_subwayInfo_dispatch(
            StationInfo_dict[data_name],
            line_배치_dict[f'{i}호선'],
            histPlot=False
            )
# line_배치_dict['7호선'].tail()

/Users/forrestdpark/Desktop/PDG/Python_/Project/HaruSijack/DataAnalysis
!Data
1. ->  StationInfo_2023-10-31.csv
2. ->  StationInfo_2022-12-31.csv
3. ->  StationInfo_22.csv
4. ->  StationInfo_23_2.csv
5. ->  StationInfo_23_0.csv
6. ->  StationInfo_23_1.csv
7. ->  StationInfo.csv
  >> 📌Data folder 에 있는 년도별 Station Info 를  StationInfo_dict 에 저장합니다.
[[StationInfo keys]]
  |- StationInfo_2023-10-31
  |- StationInfo_2022-12-31
  |- StationInfo_22
  |- StationInfo_23_2
  |- StationInfo_23_0
  |- StationInfo_23_1
  |- StationInfo
✅ StationInfo_23_0 :역사정보
    역사코드  역이름  호선  환승역수
0   150  서울역   1     2
1   426  서울역   4     2
2   151   시청   1     2
✅ StationInfo_23_0 : 역사별 위도경도 :
    역사코드   latitude   longitude
0   150  37.554679  126.970607
1   426  37.554679  126.970607
2   151  37.565345  126.977198
✅ Merged data check(tail)
     역사코드  역이름  호선  환승역수   latitude   longitude
273  2828  남위례   8     1  37.462723  127.139351
274  2649   신내   6     1  37.612491  127.104271
275  2753  까치울   7     1  37.506227  126.811340
--- 배차시간표 + 역사정보 ---
[1]호선 배차시간표 역사코드 개수 :98
[1]호선테이블 병합후 서비스가능한 총 역 개수 10
SAT을 4로 이동함
DAY을 5로 이동함
SAT,DAY -> 주말,주중
최종 병합된 테이블을 출력합니다
--- 배차시간표 + 역사정보 ---
[2]호선 배차시간표 역사코드 개수 :51
[2]호선테이블 병합후 서비스가능한 총 역 개수 50
SAT을 4로 이동함
DAY을 5로 이동함
SAT,DAY -> 주말,주중
최종 병합된 테이블을 출력합니다
--- 배차시간표 + 역사정보 ---
[3]호선 배차시간표 역사코드 개수 :44
[3]호선테이블 병합후 서비스가능한 총 역 개수 34
SAT을 4로 이동함
DAY을 5로 이동함
SAT,DAY -> 주말,주중
최종 병합된 테이블을 출력합니다
--- 배차시간표 + 역사정보 ---
[4]호선 배차시간표 역사코드 개수 :48
[4]호선테이블 병합후 서비스가능한 총 역 개수 26
SAT을 4로 이동함
DAY을 5로 이동함
SAT,DAY -> 주말,주중
최종 병합된 테이블을 출력합니다
--- 배차시간표 + 역사정보 ---
[5]호선 배차시간표 역사코드 개수 :56
[5]호선테이블 병합후 서비스가능한 총 역 개수 56
SAT을 4로 이동함
DAY을 5로 이동함
SAT,DAY -> 주말,주중
최종 병합된 테이블을 출력합니다
--- 배차시간표 + 역사정보 ---
[6]호선 배차시간표 역사코드 개수 :39
[6]호선테이블 병합후 서비스가능한 총 역 개수 39
SAT을 4로 이동함
DAY을 5로 이동함
SAT,DAY -> 주말,주중
최종 병합된 테이블을 출력합니다
--- 배차시간표 + 역사정보 ---
[7]호선 배차시간표 역사코드 개수 :53
[7]호선테이블 병합후 서비스가능한 총 역 개수 43
SAT을 4로 이동함
DAY을 5로 이동함
SAT,DAY -> 주말,주중
최종 병합된 테이블을 출력합니다
--- 배차시간표 + 역사정보 ---
[8]호선 배차시간표 역사코드 개수 :17
[8]호선테이블 병합후 서비스가능한 총 역 개수 17
SAT을 4로 이동함
DAY을 5로 이동함
SAT,DAY -> 주말,주중
최종 병합된 테이블을 출력합니다

In [3]:
# 전체학습데이터 생성 
# 기본 승하차데이터의 승하차 칼럼들을 다시 정제 해야함. 
mlTable_dict = {}
subway_dict_22_23 =np.load("../Data/DataDictionary/subway_dict_test.npy",allow_pickle=True).tolist()
for i,key in enumerate(subway_dict_22_23.keys()):
    print(Service.colored_text(f'🔹 {i} key : {key}','cyan'))
    mlTable_dict[key]= Service.data_preprocessing_toAnalysis(subway_dict_22_23,key)

print(Service.colored_text("########### 정제된 데이터에서 Feature Engineering 을 시작합니다 #################",'yellow'))

for i,key in enumerate(mlTable_dict.keys()):
    print(Service.colored_text(f'🔹 {i} key : {key}','cyan'))
    print(Service.colored_text(f">> 📌{key}data 의 수송일자 칼럼에서 요일(int)을 추출한뒤 4번째 칼럼으로 이동",'yellow'))
    mlTable_dict[key]= Service.dayToIntConvert(mlTable_dict[key], "수송일자")
    mlTable_dict[key] = Service.reorder_columns(mlTable_dict[key],col_name="요일",target_idx=4)
    
    ##날짜에서 년도,월, 주차
    mlTable_dict[key] = Service.date_Divid_Add_YMW_cols(mlTable_dict[key] ,'수송일자')
    ## 날짜에서 공휴일 데이터 추가
    mlTable_dict[key]= Service.holidaysToIntConvert(mlTable_dict[key],DateColName='수송일자')
    ## 수송일자 , 연번 삭제 시간관련데이터 앞으로 이동 
    for idx, col in enumerate(["년도","월","주차","공휴일"]):
        mlTable_dict[key] =Service.reorder_columns(col_name=col,df=mlTable_dict[key] ,target_idx=idx)
    mlTable_dict[key]['주중주말'] = ['SAT' if day in [5, 6] else 'DAY' for day in mlTable_dict[key]['요일']]
    mlTable_dict[key]=Service.reorder_columns(col_name='주중주말',df= mlTable_dict[key],target_idx=4)
# 시간대 칼럼 이름 변경 ~시 인원으로 
print(Service.colored_text("시간대 칼럼 이름 변경 ~시 인원으로",'yellow'))
for key in  mlTable_dict.keys():
    colnamelist =mlTable_dict[key].columns.tolist()
    시간대시작index=Service.indexFind(colnamelist,'06')[0]
    # print(*colnamelist[시간대시작index:])
    for colname in colnamelist[시간대시작index:]:
        # print(f'{colname[:2]}시인원')
        mlTable_dict[key].rename({colname:f'{colname[:2]}시인원'}, inplace=True, axis=1)


print(Service.colored_text("########### Feature Engineering 완료 #################",'yellow'))

🔹 0 key : subway23_0
columns ---👇
['연번', '수송일자', '호선', '역번호', '역명', '승하차구분', '06시이전', '06-07시간대', '07-08시간대', '08-09시간대', '09-10시간대', '10-11시간대', '11-12시간대', '12-13시간대', '13-14시간대', '14-15시간대', '15-16시간대', '16-17시간대', '17-18시간대', '18-19시간대', '19-20시간대', '20-21시간대', '21-22시간대', '22-23시간대', '23-24시간대', '24시이후']
 1. 연번을 삭제합니다.
 2."역명" ->"역이름", "역번호"->"역사코드 ".
 3. 호선 데이터가 object 입니다.
   - 1호선
   - 2호선
   - 3호선
 ..
 😀호선을 integer 로 만듭니다.
 3-1. 호선 을 제거한 이름 unique : , 1, 2, 3, 4, 5, 6, 7, 8
 ✅변경된 호선 칼럼의 data type : int64
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 <<< dataInfoProcessing. >>>
  1️⃣ Data row/colum numbers : 98603/25
  2️⃣ null ceck 결과Null 없는 clean data!
  3️⃣ Column  Information (중복체크)
	idx.columName |				 |Colum Info(dtype)|**
	 ----------------------------------------------------------------
	0.[수송일자(object)]: 			181/98603 [uniq/raw]
	1.[호선(int64)]: 			8/98603 [uniq/raw]
	2.[역사코드(int64)]: 			279/98603 [uniq/raw]
	3.[역이름(object)]: 			244/98603 [uniq/raw]
	4.[승하차구분(object)]: 			2/98603 [uniq/raw]
	5.[06시이전(int64)]: 			1471/98603 [uniq/raw]
	 ...etc (추가로 19개의 칼럼이 있습니다 )

 🔸🔸🔸지하철 역정보 테이블 함수 실행🔸🔸🔸
  |- 첫 수송일자 : 2023-01-01
  |- 마지막 수송일자 : 2023-06-30
[]는 값에러 0 으로 대체함
 >>StationInfo_23_0으로 저장합니다.
         수송일자  호선  역사코드  역이름 승하차구분  06시이전
0  2023-01-01   1   150  서울역    승차    215
1  2023-01-01   1   150  서울역    하차    154
2  2023-01-01   1   151   시청    승차     48
3  2023-01-01   1   151   시청    하차     64
[200]
[200]
⬇--2호선 서비스불가 역사코드 . 및 역사명--⬇
 1.200 까치산 역
--------------------
[1952, 1953, 1954, 1955, 1956, 1957, 1958, 1948, 1950, 1951]
[1952, 1953, 1954, 1955, 1956, 1957, 1958, 1948, 1950, 1951]
⬇--3호선 서비스불가 역사코드 . 및 역사명--⬇
 1.1958 대화 역
 2.1957 주엽 역
 3.1956 정발산 역
 4.1955 마두 역
 5.1954 백석 역
 6.1953 대곡 역
 7.1952 화정 역
 8.1951 원당 역
 9.1948 원흥 역
 10.1950 삼송 역
--------------------
[1450, 1451, 1452, 1453, 1454, 1455, 1456, 1457, 1458, 1751, 1752, 1753, 1754, 1755, 1756, 1757, 1758, 1759, 1760, 1761, 1762, 1763]
[1450, 1451, 1452, 1453, 1454, 1455, 1456, 1457, 1458, 1751, 1752, 1753, 1754, 1755, 1756, 1757, 1758, 1759, 1760, 1761, 1762, 1763]
⬇--4호선 서비스불가 역사코드 . 및 역사명--⬇
 1.1450 선바위 역
 2.1451 경마공원 역
 3.1452 대공원 역
 4.1453 과천 역
 5.1454 정부과천청사 역
 6.1455 인덕원 역
 7.1456 평촌 역
 8.1457 범계 역
 9.1458 금정 역
 10.1751 산본 역
 11.1763 수리산 역
 12.1752 대야미 역
 13.1753 반월 역
 14.1754 상록수 역
 15.1755 한대앞 역
 16.1756 중앙 역
 17.1757 고잔 역
 18.1758 초지 역
 19.1759 안산 역
 20.1760 신길온천 역
 21.1761 정왕 역
 22.1762 오이도 역
--------------------
[]
[]
[]
[]
[2754, 2757, 2758, 2760, 2761, 3762, 3763]
[2754, 2757, 2758, 2760, 2761, 3762, 3763]
⬇--7호선 서비스불가 역사코드 . 및 역사명--⬇
 1.3763 석남 역
 2.3762 산곡 역
 3.2761 부평구청 역
 4.2760 굴포천 역
 5.2758 상동 역
 6.2757 부천시청 역
 7.2754 부천종합운동장 역
--------------------
배차 시간 제공 역 개수:  394
 호선 -> 1 2 3 4 5 6 7 8 9
호선을 1로 이동함
 🔸[1]호선 에 대한 배차 테이블 표정제 결과
배차정보를 저장합니다.
시간  역사코드  호선 주중주말   05    06    07
0    150   1  DAY  5.5  13.5  16.5
1    150   1  SAT  4.5  10.0  13.0
2    151   1  DAY  7.0  15.0  15.0
호선을 1로 이동함
 🔸[2]호선 에 대한 배차 테이블 표정제 결과
배차정보를 저장합니다.
시간  역사코드  호선 주중주말   05   06   07
0    200   2  DAY  1.0  2.0  3.0
1    200   2  END  1.0  2.0  3.0
2    200   2  SAT  1.0  2.0  3.0
호선을 1로 이동함
 🔸[3]호선 에 대한 배차 테이블 표정제 결과
배차정보를 저장합니다.
시간  역사코드  호선 주중주말   05    06    07
0    309   3  DAY  3.0  12.0  16.0
1    309   3  SAT  2.0   8.0  12.0
2    310   3  DAY  2.0  14.0  22.0
호선을 1로 이동함
 🔸[4]호선 에 대한 배차 테이블 표정제 결과
배차정보를 저장합니다.
시간  역사코드  호선 주중주말   05    06    07
0    409   4  DAY  0.0   5.0  11.0
1    409   4  SAT  2.0   9.5  14.0
2    410   4  DAY  4.0  17.5  25.0
호선을 1로 이동함
 🔸[5]호선 에 대한 배차 테이블 표정제 결과
배차정보를 저장합니다.
시간  역사코드  호선 주중주말   05   06    07
0   2511   5  DAY  0.5  2.5   5.5
1   2511   5  SAT  0.5  2.5   4.5
2   2512   5  DAY  3.0  9.0  15.5
호선을 1로 이동함
 🔸[6]호선 에 대한 배차 테이블 표정제 결과
배차정보를 저장합니다.
시간  역사코드  호선 주중주말   05   06    07
0   2611   6  DAY  2.0  8.0  11.5
1   2611   6  SAT  2.0  8.0   7.0
2   2612   6  DAY  1.5  4.0   5.5
호선을 1로 이동함
 🔸[7]호선 에 대한 배차 테이블 표정제 결과
배차정보를 저장합니다.
시간  역사코드  호선 주중주말   05   06    07
0   2711   7  DAY  0.5  2.5   2.5
1   2711   7  SAT  0.5  2.0   1.5
2   2712   7  DAY  2.5  7.5  14.0
호선을 1로 이동함
 🔸[8]호선 에 대한 배차 테이블 표정제 결과
배차정보를 저장합니다.
시간  역사코드  호선 주중주말   05   06    07
0   2811   8  DAY  1.0  3.5   5.5
1   2811   8  SAT  1.0  3.5   3.5
2   2812   8  DAY  3.0  7.0  11.0
🔹 1 key : subway23_1
columns ---👇
['연번', '수송일자', '호선', '역번호', '역명', '승하차구분', '06시이전', '06-07시간대', '07-08시간대', '08-09시간대', '09-10시간대', '10-11시간대', '11-12시간대', '12-13시간대', '13-14시간대', '14-15시간대', '15-16시간대', '16-17시간대', '17-18시간대', '18-19시간대', '19-20시간대', '20-21시간대', '21-22시간대', '22-23시간대', '23-24시간대', '24시이후']
 1. 연번을 삭제합니다.
 2."역명" ->"역이름", "역번호"->"역사코드 ".
 3. 호선 데이터가 object 입니다.
   - 1호선
   - 2호선
   - 3호선
 ..
 😀호선을 integer 로 만듭니다.
 3-1. 호선 을 제거한 이름 unique : , 1, 2, 3, 4, 5, 6, 7, 8
 ✅변경된 호선 칼럼의 data type : int64
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 <<< dataInfoProcessing. >>>
  1️⃣ Data row/colum numbers : 165376/25
  2️⃣ null ceck 결과Null 없는 clean data!
  3️⃣ Column  Information (중복체크)
	idx.columName |				 |Colum Info(dtype)|**
	 ----------------------------------------------------------------
	0.[수송일자(object)]: 			304/165376 [uniq/raw]
	1.[호선(int64)]: 			8/165376 [uniq/raw]
	2.[역사코드(int64)]: 			272/165376 [uniq/raw]
	3.[역이름(object)]: 			239/165376 [uniq/raw]
	4.[승하차구분(object)]: 			2/165376 [uniq/raw]
	5.[06시이전(int64)]: 			1596/165376 [uniq/raw]
	 ...etc (추가로 19개의 칼럼이 있습니다 )

 🔸🔸🔸지하철 역정보 테이블 함수 실행🔸🔸🔸
  |- 첫 수송일자 : 2023-01-01
  |- 마지막 수송일자 : 2023-10-31
[]는 값에러 0 으로 대체함
 >>StationInfo_23_1으로 저장합니다.
         수송일자  호선  역사코드  역이름 승하차구분  06시이전
0  2023-01-01   1   150  서울역    승차    215
1  2023-01-01   1   150  서울역    하차    154
2  2023-01-01   1   151   시청    승차     48
3  2023-01-01   1   151   시청    하차     64
[200]
[200]
⬇--2호선 서비스불가 역사코드 . 및 역사명--⬇
 1.200 까치산 역
--------------------
[1952, 1953, 1954, 1955, 1956, 1957, 1958, 321, 1948, 1950, 1951]
[1952, 1953, 1954, 1955, 1956, 1957, 1958, 321, 1948, 1950, 1951]
⬇--3호선 서비스불가 역사코드 . 및 역사명--⬇
 1.1958 대화 역
 2.1957 주엽 역
 3.1956 정발산 역
 4.1955 마두 역
 5.1954 백석 역
 6.1953 대곡 역
 7.1952 화정 역
 8.1951 원당 역
 9.1948 원흥 역
 10.1950 삼송 역
 11.321 충무로 역
--------------------
[1450, 1451, 1452, 1453, 1454, 1455, 1456, 1457, 1458, 1751, 1752, 1753, 1754, 1755, 1756, 1757, 1758, 1759, 1760, 1761, 1762, 1763]
[1450, 1451, 1452, 1453, 1454, 1455, 1456, 1457, 1458, 1751, 1752, 1753, 1754, 1755, 1756, 1757, 1758, 1759, 1760, 1761, 1762, 1763]
⬇--4호선 서비스불가 역사코드 . 및 역사명--⬇
 1.1450 선바위 역
 2.1451 경마공원 역
 3.1452 대공원 역
 4.1453 과천 역
 5.1454 정부과천청사 역
 6.1455 인덕원 역
 7.1456 평촌 역
 8.1457 범계 역
 9.1458 금정 역
 10.1751 산본 역
 11.1763 수리산 역
 12.1752 대야미 역
 13.1753 반월 역
 14.1754 상록수 역
 15.1755 한대앞 역
 16.1756 중앙 역
 17.1757 고잔 역
 18.1758 초지 역
 19.1759 안산 역
 20.1760 신길온천 역
 21.1761 정왕 역
 22.1762 오이도 역
--------------------
[]
[]
[2649, 2615]
[2649, 2615]
⬇--6호선 서비스불가 역사코드 . 및 역사명--⬇
 1.2649 신내 역
 2.2615 연신내 역
--------------------
[2753, 2754, 2755, 2756, 2757, 2758, 2759, 2760, 2761, 3762, 3763]
[2753, 2754, 2755, 2756, 2757, 2758, 2759, 2760, 2761, 3762, 3763]
⬇--7호선 서비스불가 역사코드 . 및 역사명--⬇
 1.3763 석남 역
 2.3762 산곡 역
 3.2761 부평구청 역
 4.2760 굴포천 역
 5.2759 삼산체육관 역
 6.2758 상동 역
 7.2757 부천시청 역
 8.2756 신중동 역
 9.2755 춘의 역
 10.2754 부천종합운동장 역
 11.2753 까치울 역
--------------------
배차 시간 제공 역 개수:  394
 호선 -> 1 2 3 4 5 6 7 8 9
호선을 1로 이동함
 🔸[1]호선 에 대한 배차 테이블 표정제 결과
배차정보를 저장합니다.
시간  역사코드  호선 주중주말   05    06    07
0    150   1  DAY  5.5  13.5  16.5
1    150   1  SAT  4.5  10.0  13.0
2    151   1  DAY  7.0  15.0  15.0
호선을 1로 이동함
 🔸[2]호선 에 대한 배차 테이블 표정제 결과
배차정보를 저장합니다.
시간  역사코드  호선 주중주말   05   06   07
0    200   2  DAY  1.0  2.0  3.0
1    200   2  END  1.0  2.0  3.0
2    200   2  SAT  1.0  2.0  3.0
호선을 1로 이동함
 🔸[3]호선 에 대한 배차 테이블 표정제 결과
배차정보를 저장합니다.
시간  역사코드  호선 주중주말   05    06    07
0    309   3  DAY  3.0  12.0  16.0
1    309   3  SAT  2.0   8.0  12.0
2    310   3  DAY  2.0  14.0  22.0
호선을 1로 이동함
 🔸[4]호선 에 대한 배차 테이블 표정제 결과
배차정보를 저장합니다.
시간  역사코드  호선 주중주말   05    06    07
0    409   4  DAY  0.0   5.0  11.0
1    409   4  SAT  2.0   9.5  14.0
2    410   4  DAY  4.0  17.5  25.0
호선을 1로 이동함
 🔸[5]호선 에 대한 배차 테이블 표정제 결과
배차정보를 저장합니다.
시간  역사코드  호선 주중주말   05   06    07
0   2511   5  DAY  0.5  2.5   5.5
1   2511   5  SAT  0.5  2.5   4.5
2   2512   5  DAY  3.0  9.0  15.5
호선을 1로 이동함
 🔸[6]호선 에 대한 배차 테이블 표정제 결과
배차정보를 저장합니다.
시간  역사코드  호선 주중주말   05   06    07
0   2611   6  DAY  2.0  8.0  11.5
1   2611   6  SAT  2.0  8.0   7.0
2   2612   6  DAY  1.5  4.0   5.5
호선을 1로 이동함
 🔸[7]호선 에 대한 배차 테이블 표정제 결과
배차정보를 저장합니다.
시간  역사코드  호선 주중주말   05   06    07
0   2711   7  DAY  0.5  2.5   2.5
1   2711   7  SAT  0.5  2.0   1.5
2   2712   7  DAY  2.5  7.5  14.0
호선을 1로 이동함
 🔸[8]호선 에 대한 배차 테이블 표정제 결과
배차정보를 저장합니다.
시간  역사코드  호선 주중주말   05   06    07
0   2811   8  DAY  1.0  3.5   5.5
1   2811   8  SAT  1.0  3.5   3.5
2   2812   8  DAY  3.0  7.0  11.0
🔹 2 key : subway23_2
columns ---👇
['연번', '날짜', '호선', '역번호', '역명', '구분', '06시 이전', '06시-07시', '07시-08시', '08시-09시', '09시-10시', '10시-11시', '11시-12시', '12시-13시', '13시-14시', '14시-15시', '15시-16시', '16시-17시', '17시-18시', '18시-19시', '19시-20시', '20시-21시', '21시-22시', '22시-23시', '23시-24시', '24시 이후']
 1. 연번을 삭제합니다.
 2."역명" ->"역이름", "역번호"->"역사코드 ".
 3. 호선 데이터가 object 입니다.
   - 1호선
   - 2호선
   - 3호선
 ..
 😀호선을 integer 로 만듭니다.
 3-1. 호선 을 제거한 이름 unique : , 1, 2, 3, 4, 5, 6, 7, 8
 ✅변경된 호선 칼럼의 data type : int64
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 <<< dataInfoProcessing. >>>
  1️⃣ Data row/colum numbers : 50238/25
  2️⃣ null ceck 결과Null 없는 clean data!
  3️⃣ Column  Information (중복체크)
	idx.columName |				 |Colum Info(dtype)|**
	 ----------------------------------------------------------------
	0.[수송일자(object)]: 			92/50238 [uniq/raw]
	1.[호선(int64)]: 			8/50238 [uniq/raw]
	2.[역사코드(int64)]: 			278/50238 [uniq/raw]
	3.[역이름(object)]: 			244/50238 [uniq/raw]
	4.[구분(object)]: 			2/50238 [uniq/raw]
	5.[06시 이전(int64)]: 			1248/50238 [uniq/raw]
	 ...etc (추가로 19개의 칼럼이 있습니다 )

 🔸🔸🔸지하철 역정보 테이블 함수 실행🔸🔸🔸
  |- 첫 수송일자 : 2023-11-01
  |- 마지막 수송일자 : 2024-01-31
[]는 값에러 0 으로 대체함
 >>StationInfo_23_2으로 저장합니다.
         수송일자  호선  역사코드  역이름  구분  06시 이전
0  2023-11-01   1   150  서울역  승차     342
1  2023-11-01   1   150  서울역  하차     300
2  2023-11-01   1   151   시청  승차      86
3  2023-11-01   1   151   시청  하차     220
[200]
[200]
⬇--2호선 서비스불가 역사코드 . 및 역사명--⬇
 1.200 까치산 역
--------------------
[1952, 1953, 1954, 1955, 1956, 1957, 1958, 1948, 1950, 1951]
[1952, 1953, 1954, 1955, 1956, 1957, 1958, 1948, 1950, 1951]
⬇--3호선 서비스불가 역사코드 . 및 역사명--⬇
 1.1958 대화 역
 2.1957 주엽 역
 3.1956 정발산 역
 4.1955 마두 역
 5.1954 백석 역
 6.1953 대곡 역
 7.1952 화정 역
 8.1951 원당 역
 9.1948 원흥 역
 10.1950 삼송 역
--------------------
[1450, 1451, 1452, 1453, 1454, 1455, 1456, 1457, 1458, 1751, 1752, 1753, 1754, 1755, 1756, 1757, 1758, 1759, 1760, 1761, 1762, 1763]
[1450, 1451, 1452, 1453, 1454, 1455, 1456, 1457, 1458, 1751, 1752, 1753, 1754, 1755, 1756, 1757, 1758, 1759, 1760, 1761, 1762, 1763]
⬇--4호선 서비스불가 역사코드 . 및 역사명--⬇
 1.1450 선바위 역
 2.1451 경마공원 역
 3.1452 대공원 역
 4.1453 과천 역
 5.1454 정부과천청사 역
 6.1455 인덕원 역
 7.1456 평촌 역
 8.1457 범계 역
 9.1458 금정 역
 10.1751 산본 역
 11.1763 수리산 역
 12.1752 대야미 역
 13.1753 반월 역
 14.1754 상록수 역
 15.1755 한대앞 역
 16.1756 중앙 역
 17.1757 고잔 역
 18.1758 초지 역
 19.1759 안산 역
 20.1760 신길온천 역
 21.1761 정왕 역
 22.1762 오이도 역
--------------------
[]
[]
[]
[]
[2754, 2755, 2756, 2758, 2759, 2761, 3762, 3763]
[2754, 2755, 2756, 2758, 2759, 2761, 3762, 3763]
⬇--7호선 서비스불가 역사코드 . 및 역사명--⬇
 1.3763 석남 역
 2.3762 산곡 역
 3.2761 부평구청 역
 4.2759 삼산체육관 역
 5.2758 상동 역
 6.2756 신중동 역
 7.2755 춘의 역
 8.2754 부천종합운동장 역
--------------------
배차 시간 제공 역 개수:  394
 호선 -> 1 2 3 4 5 6 7 8 9
호선을 1로 이동함
 🔸[1]호선 에 대한 배차 테이블 표정제 결과
배차정보를 저장합니다.
시간  역사코드  호선 주중주말   05    06    07
0    150   1  DAY  5.5  13.5  16.5
1    150   1  SAT  4.5  10.0  13.0
2    151   1  DAY  7.0  15.0  15.0
호선을 1로 이동함
 🔸[2]호선 에 대한 배차 테이블 표정제 결과
배차정보를 저장합니다.
시간  역사코드  호선 주중주말   05   06   07
0    200   2  DAY  1.0  2.0  3.0
1    200   2  END  1.0  2.0  3.0
2    200   2  SAT  1.0  2.0  3.0
호선을 1로 이동함
 🔸[3]호선 에 대한 배차 테이블 표정제 결과
배차정보를 저장합니다.
시간  역사코드  호선 주중주말   05    06    07
0    309   3  DAY  3.0  12.0  16.0
1    309   3  SAT  2.0   8.0  12.0
2    310   3  DAY  2.0  14.0  22.0
호선을 1로 이동함
 🔸[4]호선 에 대한 배차 테이블 표정제 결과
배차정보를 저장합니다.
시간  역사코드  호선 주중주말   05    06    07
0    409   4  DAY  0.0   5.0  11.0
1    409   4  SAT  2.0   9.5  14.0
2    410   4  DAY  4.0  17.5  25.0
호선을 1로 이동함
 🔸[5]호선 에 대한 배차 테이블 표정제 결과
배차정보를 저장합니다.
시간  역사코드  호선 주중주말   05   06    07
0   2511   5  DAY  0.5  2.5   5.5
1   2511   5  SAT  0.5  2.5   4.5
2   2512   5  DAY  3.0  9.0  15.5
호선을 1로 이동함
 🔸[6]호선 에 대한 배차 테이블 표정제 결과
배차정보를 저장합니다.
시간  역사코드  호선 주중주말   05   06    07
0   2611   6  DAY  2.0  8.0  11.5
1   2611   6  SAT  2.0  8.0   7.0
2   2612   6  DAY  1.5  4.0   5.5
호선을 1로 이동함
 🔸[7]호선 에 대한 배차 테이블 표정제 결과
배차정보를 저장합니다.
시간  역사코드  호선 주중주말   05   06    07
0   2711   7  DAY  0.5  2.5   2.5
1   2711   7  SAT  0.5  2.0   1.5
2   2712   7  DAY  2.5  7.5  14.0
호선을 1로 이동함
 🔸[8]호선 에 대한 배차 테이블 표정제 결과
배차정보를 저장합니다.
시간  역사코드  호선 주중주말   05   06    07
0   2811   8  DAY  1.0  3.5   5.5
1   2811   8  SAT  1.0  3.5   3.5
2   2812   8  DAY  3.0  7.0  11.0
🔹 3 key : subway22
columns ---👇
['연번', '수송일자', '호선', '고유역번호(외부역코드)', '역명', '승하차구분', '06시이전', '06-07시간대', '07-08시간대', '08-09시간대', '09-10시간대', '10-11시간대', '11-12시간대', '12-13시간대', '13-14시간대', '14-15시간대', '15-16시간대', '16-17시간대', '17-18시간대', '18-19시간대', '19-20시간대', '20-21시간대', '21-22시간대', '22-23시간대', '23-24시간대', '24시이후']
 1. 연번을 삭제합니다.
 2."역명" ->"역이름", "역번호"->"역사코드 ".
3. 호선 데이터가 integer 입니다.
 - 1
 - 2
 - 3
 ..
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 <<< dataInfoProcessing. >>>
  1️⃣ Data row/colum numbers : 199080/25
  2️⃣ null ceck 결과총 82346개의 null 이 있습니다!
   => 24번째.[24시이후]컬럼 :  null 82346 개,	 not null 116734 개
  3️⃣ Column  Information (중복체크)
	idx.columName |				 |Colum Info(dtype)|**
	 ----------------------------------------------------------------
	0.[수송일자(object)]: 			365/199080 [uniq/raw]
	1.[호선(int64)]: 			8/199080 [uniq/raw]
	2.[고유역번호(외부역코드)(object)]: 		558/199080 [uniq/raw]
	3.[역이름(object)]: 			244/199080 [uniq/raw]
	4.[승하차구분(object)]: 			2/199080 [uniq/raw]
	5.[06시이전(int64)]: 			1596/199080 [uniq/raw]
	 ...etc (추가로 19개의 칼럼이 있습니다 )

 🔸🔸🔸지하철 역정보 테이블 함수 실행🔸🔸🔸
  |- 첫 수송일자 : 2022-01-01
  |- 마지막 수송일자 : 2022-12-31
132480번째 데이터   <-value errer:
[132480]는 값에러 0 으로 대체함
 >>StationInfo_22으로 저장합니다.
         수송일자  호선 고유역번호(외부역코드)  역이름 승하차구분  06시이전
0  2022-01-01   1          150  서울역    승차    120
1  2022-01-01   1          150  서울역    하차    113
2  2022-01-01   1          151   시청    승차     38
3  2022-01-01   1          151   시청    하차     31
[200]
[200]
⬇--2호선 서비스불가 역사코드 . 및 역사명--⬇
 1.200 까치산 역
--------------------
[1952, 1953, 1954, 1955, 1956, 1957, 1958, 1948, 1950, 1951]
[1952, 1953, 1954, 1955, 1956, 1957, 1958, 1948, 1950, 1951]
⬇--3호선 서비스불가 역사코드 . 및 역사명--⬇
 1.1958 대화 역
 2.1957 주엽 역
 3.1956 정발산 역
 4.1955 마두 역
 5.1954 백석 역
 6.1953 대곡 역
 7.1952 화정 역
 8.1951 원당 역
 9.1948 원흥 역
 10.1950 삼송 역
--------------------
[1450, 1451, 1452, 1453, 1454, 1455, 1456, 1457, 1458, 1751, 1752, 1753, 1754, 1755, 1756, 1757, 1758, 1759, 1760, 1761, 1762, 1763]
[1450, 1451, 1452, 1453, 1454, 1455, 1456, 1457, 1458, 1751, 1752, 1753, 1754, 1755, 1756, 1757, 1758, 1759, 1760, 1761, 1762, 1763]
⬇--4호선 서비스불가 역사코드 . 및 역사명--⬇
 1.1450 선바위 역
 2.1451 경마공원 역
 3.1452 대공원 역
 4.1453 과천 역
 5.1454 정부과천청사 역
 6.1455 인덕원 역
 7.1456 평촌 역
 8.1457 범계 역
 9.1458 금정 역
 10.1751 산본 역
 11.1763 수리산 역
 12.1752 대야미 역
 13.1753 반월 역
 14.1754 상록수 역
 15.1755 한대앞 역
 16.1756 중앙 역
 17.1757 고잔 역
 18.1758 초지 역
 19.1759 안산 역
 20.1760 신길온천 역
 21.1761 정왕 역
 22.1762 오이도 역
--------------------
[]
[]
[]
[]
[2754, 2755, 2756, 2759, 2760, 3762, 3763]
[2754, 2755, 2756, 2759, 2760, 3762, 3763]
⬇--7호선 서비스불가 역사코드 . 및 역사명--⬇
 1.3763 석남 역
 2.3762 산곡 역
 3.2760 굴포천 역
 4.2759 삼산체육관 역
 5.2756 신중동 역
 6.2755 춘의 역
 7.2754 부천종합운동장 역
--------------------
배차 시간 제공 역 개수:  394
 호선 -> 1 2 3 4 5 6 7 8 9
호선을 1로 이동함
 🔸[1]호선 에 대한 배차 테이블 표정제 결과
배차정보를 저장합니다.
시간  역사코드  호선 주중주말   05    06    07
0    150   1  DAY  5.5  13.5  16.5
1    150   1  SAT  4.5  10.0  13.0
2    151   1  DAY  7.0  15.0  15.0
호선을 1로 이동함
 🔸[2]호선 에 대한 배차 테이블 표정제 결과
배차정보를 저장합니다.
시간  역사코드  호선 주중주말   05   06   07
0    200   2  DAY  1.0  2.0  3.0
1    200   2  END  1.0  2.0  3.0
2    200   2  SAT  1.0  2.0  3.0
호선을 1로 이동함
 🔸[3]호선 에 대한 배차 테이블 표정제 결과
배차정보를 저장합니다.
시간  역사코드  호선 주중주말   05    06    07
0    309   3  DAY  3.0  12.0  16.0
1    309   3  SAT  2.0   8.0  12.0
2    310   3  DAY  2.0  14.0  22.0
호선을 1로 이동함
 🔸[4]호선 에 대한 배차 테이블 표정제 결과
배차정보를 저장합니다.
시간  역사코드  호선 주중주말   05    06    07
0    409   4  DAY  0.0   5.0  11.0
1    409   4  SAT  2.0   9.5  14.0
2    410   4  DAY  4.0  17.5  25.0
호선을 1로 이동함
 🔸[5]호선 에 대한 배차 테이블 표정제 결과
배차정보를 저장합니다.
시간  역사코드  호선 주중주말   05   06    07
0   2511   5  DAY  0.5  2.5   5.5
1   2511   5  SAT  0.5  2.5   4.5
2   2512   5  DAY  3.0  9.0  15.5
호선을 1로 이동함
 🔸[6]호선 에 대한 배차 테이블 표정제 결과
배차정보를 저장합니다.
시간  역사코드  호선 주중주말   05   06    07
0   2611   6  DAY  2.0  8.0  11.5
1   2611   6  SAT  2.0  8.0   7.0
2   2612   6  DAY  1.5  4.0   5.5
호선을 1로 이동함
 🔸[7]호선 에 대한 배차 테이블 표정제 결과
배차정보를 저장합니다.
시간  역사코드  호선 주중주말   05   06    07
0   2711   7  DAY  0.5  2.5   2.5
1   2711   7  SAT  0.5  2.0   1.5
2   2712   7  DAY  2.5  7.5  14.0
호선을 1로 이동함
 🔸[8]호선 에 대한 배차 테이블 표정제 결과
배차정보를 저장합니다.
시간  역사코드  호선 주중주말   05   06    07
0   2811   8  DAY  1.0  3.5   5.5
1   2811   8  SAT  1.0  3.5   3.5
2   2812   8  DAY  3.0  7.0  11.0
########### 정제된 데이터에서 Feature Engineering 을 시작합니다 #################
🔹 0 key : subway23_0
>> 📌subway23_0data 의 수송일자 칼럼에서 요일(int)을 추출한뒤 4번째 칼럼으로 이동
요일을 4로 이동함
년도을 0로 이동함
월을 1로 이동함
주차을 2로 이동함
공휴일을 3로 이동함
주중주말을 4로 이동함
🔹 1 key : subway23_1
>> 📌subway23_1data 의 수송일자 칼럼에서 요일(int)을 추출한뒤 4번째 칼럼으로 이동
요일을 4로 이동함
년도을 0로 이동함
월을 1로 이동함
주차을 2로 이동함
공휴일을 3로 이동함
주중주말을 4로 이동함
🔹 2 key : subway23_2
>> 📌subway23_2data 의 수송일자 칼럼에서 요일(int)을 추출한뒤 4번째 칼럼으로 이동
요일을 4로 이동함
년도을 0로 이동함
월을 1로 이동함
주차을 2로 이동함
공휴일을 3로 이동함
주중주말을 4로 이동함
🔹 3 key : subway22
>> 📌subway22data 의 수송일자 칼럼에서 요일(int)을 추출한뒤 4번째 칼럼으로 이동
요일을 4로 이동함
년도을 0로 이동함
월을 1로 이동함
주차을 2로 이동함
공휴일을 3로 이동함
주중주말을 4로 이동함
시간대 칼럼 이름 변경 ~시 인원으로
########### Feature Engineering 완료 #################

In [4]:
# 시간대 칼럼 이름 변경 
#index findeing
def indexFind(colnamelist, search_target_word):
    # 해당 단어가 존재하는 칼럼의 이름이있는 칼럼의 indx를 출력합니다. 
    indices = np.where([search_target_word in col for col in colnamelist])[0]
    return indices

colnamelist = mlTable_dict['subway23_0'].columns.tolist()
시간대시작index =indexFind(colnamelist,'06')[0]
print(시간대시작index)

# Service.reorder_columns(target_idx=,col_name='주중주말',df=mlTable_dict['subway23_0'])

# 
for key in  mlTable_dict.keys():
    colnamelist =mlTable_dict[key].columns.tolist()
    시간대시작index=Service.indexFind(colnamelist,'06')[0]
    # print(*colnamelist[시간대시작index:])
    for colname in colnamelist[시간대시작index:]:
        # print(f'{colname[:2]}시인원')
        mlTable_dict[key].rename({colname:f'{colname[:2]}시인원'}, inplace=True, axis=1)

mlTable_dict['subway23_0'].columns

11

Index(['년도', '월', '주차', '공휴일', '주중주말', '수송일자', '호선', '역사코드', '역이름', '요일',
       '승하차구분', '06시인원', '06시인원', '07시인원', '08시인원', '09시인원', '10시인원', '11시인원',
       '12시인원', '13시인원', '14시인원', '15시인원', '16시인원', '17시인원', '18시인원', '19시인원',
       '20시인원', '21시인원', '22시인원', '23시인원', '24시인원'],
      dtype='object')

In [5]:
for i in line_배치_dict.keys():
    print(line_배치_dict[i].columns)

Index(['역사코드', '역이름', '호선', '환승역수', '주말', '주중', 'latitude', 'longitude',
       '주중주말', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14',
       '15', '16', '17', '18', '19', '20', '21', '22', '23', '24'],
      dtype='object')
Index(['역사코드', '역이름', '호선', '환승역수', '주말', '주중', 'latitude', 'longitude',
       '주중주말', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14',
       '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', 'END'],
      dtype='object')
Index(['역사코드', '역이름', '호선', '환승역수', '주말', '주중', 'latitude', 'longitude',
       '주중주말', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14',
       '15', '16', '17', '18', '19', '20', '21', '22', '23', '24'],
      dtype='object')
Index(['역사코드', '역이름', '호선', '환승역수', '주말', '주중', 'latitude', 'longitude',
       '주중주말', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14',
       '15', '16', '17', '18', '19', '20', '21', '22', '23', '24'],
      dtype='object')
Index(['역사코드', '역이름', '호선', '환승역수', '주말', '주중', 'latitude', 'longitude',
       '주중주말', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14',
       '15', '16', '17', '18', '19', '20', '21', '22', '23', '24'],
      dtype='object')
Index(['역사코드', '역이름', '호선', '환승역수', '주말', '주중', 'latitude', 'longitude',
       '주중주말', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14',
       '15', '16', '17', '18', '19', '20', '21', '22', '23', '24'],
      dtype='object')
Index(['역사코드', '역이름', '호선', '환승역수', '주말', '주중', 'latitude', 'longitude',
       '주중주말', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14',
       '15', '16', '17', '18', '19', '20', '21', '22', '23', '24'],
      dtype='object')
Index(['역사코드', '역이름', '호선', '환승역수', '주말', '주중', 'latitude', 'longitude',
       '주중주말', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14',
       '15', '16', '17', '18', '19', '20', '21', '22', '23', '24'],
      dtype='object')

In [6]:
# 배차시간표는 Line 별로되어있기때문에 나눠서 머신러닝 만듬... 

for key in mlTable_dict.keys():
    mlTable=mlTable_dict[key]
    
    mlTable_line_dict  ={}
    for line in range(1,9):
        print(mlTable[mlTable['호선']==line])
        try: 
            mlt= mlTable[mlTable['호선']==line]
            print(mlt.columns)
            mlTable_line_dict[f'{key}_{line}호선']= pd.merge(line_배치_dict[f'{line}호선'],mlt,on = ['역사코드','주중주말','호선','역이름'])
        except: pass
    mlTable_dict[key]=mlTable_line_dict
mlTable_dict['subway23_0']

         년도  월  주차  공휴일 주중주말        수송일자  호선  역사코드  역이름  요일  ... 15시인원  16시인원  \
0      2022  1  52    0  DAY  2023-01-01   1   150  서울역   0  ...  2655   2509
1      2022  1  52    0  DAY  2023-01-01   1   150  서울역   0  ...  2282   2295
2      2022  1  52    0  DAY  2023-01-01   1   151   시청   0  ...   843    895
3      2022  1  52    0  DAY  2023-01-01   1   151   시청   0  ...   602    575
4      2022  1  52    0  DAY  2023-01-01   1   152   종각   0  ...  1145   1402
...     ... ..  ..  ...  ...         ...  ..   ...  ...  ..  ...   ...    ...
98072  2023  6  26    1  SAT  2023-06-30   1   157  제기동   5  ...  1446   1162
98073  2023  6  26    1  SAT  2023-06-30   1   158  청량리   5  ...  1665   1847
98074  2023  6  26    1  SAT  2023-06-30   1   158  청량리   5  ...  1584   1456
98075  2023  6  26    1  SAT  2023-06-30   1   159  동묘앞   5  ...   833    965
98076  2023  6  26    1  SAT  2023-06-30   1   159  동묘앞   5  ...   723    683

       17시인원  18시인원  19시인원  20시인원  21시인원  22시인원  23시인원  24시인원
0       2696   2549   2462   2177   2190   1808    734      7
1       2526   1930   1897   1487    991    609    280     46
2        959    985    670    630    515    330    146      0
3        533    456    285    267    246    154     79     18
4       1223   1272    911    913    906    602    232      3
...      ...    ...    ...    ...    ...    ...    ...    ...
98072   1086   1058    742    407    395    375    303     63
98073   1964   1771    894    720    579    366    173     17
98074   1661   1861   1485    694    700    681    454    241
98075   1091    864    450    253    231    144     54      3
98076    608    422    316    170    222    248    160    108

[3620 rows x 31 columns]
Index(['년도', '월', '주차', '공휴일', '주중주말', '수송일자', '호선', '역사코드', '역이름', '요일',
       '승하차구분', '06시인원', '06시인원', '07시인원', '08시인원', '09시인원', '10시인원', '11시인원',
       '12시인원', '13시인원', '14시인원', '15시인원', '16시인원', '17시인원', '18시인원', '19시인원',
       '20시인원', '21시인원', '22시인원', '23시인원', '24시인원'],
      dtype='object')
         년도  월  주차  공휴일 주중주말        수송일자  호선  역사코드    역이름  요일  ... 15시인원  \
20     2022  1  52    0  DAY  2023-01-01   2   201     시청   0  ...   601
21     2022  1  52    0  DAY  2023-01-01   2   201     시청   0  ...   450
22     2022  1  52    0  DAY  2023-01-01   2   202  을지로입구   0  ...  1372
23     2022  1  52    0  DAY  2023-01-01   2   202  을지로입구   0  ...  1145
24     2022  1  52    0  DAY  2023-01-01   2   203  을지로3가   0  ...   774
...     ... ..  ..  ...  ...         ...  ..   ...    ...  ..  ...   ...
98172  2023  6  26    1  SAT  2023-06-30   2   248   양천구청   5  ...   431
98173  2023  6  26    1  SAT  2023-06-30   2   249  신정네거리   5  ...   441
98174  2023  6  26    1  SAT  2023-06-30   2   249  신정네거리   5  ...   637
98175  2023  6  26    1  SAT  2023-06-30   2   250     용두   5  ...   169
98176  2023  6  26    1  SAT  2023-06-30   2   250     용두   5  ...   146

       16시인원  17시인원  18시인원  19시인원  20시인원  21시인원  22시인원  23시인원  24시인원
20       627    761    801    581    507    503    304    145      1
21       371    354    308    227    232    237    208     99     13
22      1556   1687   1901   1347   1333   1162   1029    346      7
23      1319   1289   1082    874    732    612    414    200    181
24       847    748    714    554    508    423    366    202      0
...      ...    ...    ...    ...    ...    ...    ...    ...    ...
98172    482    779   1086    970    508    449    421    432    197
98173    458    532    558    306    232    198    164     76     31
98174    857   1160   1931   1453    781    699    654    604    250
98175    186    226    283    114     58     61     35     13      5
98176    191    200    314    181    109    114    101     86     46

[18100 rows x 31 columns]
Index(['년도', '월', '주차', '공휴일', '주중주말', '수송일자', '호선', '역사코드', '역이름', '요일',
       '승하차구분', '06시인원', '06시인원', '07시인원', '08시인원', '09시인원', '10시인원', '11시인원',
       '12시인원', '13시인원', '14시인원', '15시인원', '16시인원', '17시인원', '18시인원', '19시인원',
       '20시인원', '21시인원', '22시인원', '23시인원', '24시인원'],
      dtype='object')
         년도  월  주차  공휴일 주중주말        수송일자  호선  역사코드   역이름  요일  ... 15시인원  \
120    2022  1  52    0  DAY  2023-01-01   3   309    지축   0  ...   207
121    2022  1  52    0  DAY  2023-01-01   3   309    지축   0  ...   204
122    2022  1  52    0  DAY  2023-01-01   3   310   구파발   0  ...   878
123    2022  1  52    0  DAY  2023-01-01   3   310   구파발   0  ...   721
124    2022  1  52    0  DAY  2023-01-01   3   311   연신내   0  ...  1353
...     ... ..  ..  ...  ...         ...  ..   ...   ...  ..  ...   ...
98240  2023  6  26    1  SAT  2023-06-30   3   340  가락시장   5  ...   520
98241  2023  6  26    1  SAT  2023-06-30   3   341  경찰병원   5  ...   389
98242  2023  6  26    1  SAT  2023-06-30   3   341  경찰병원   5  ...   319
98243  2023  6  26    1  SAT  2023-06-30   3   342    오금   5  ...   290
98244  2023  6  26    1  SAT  2023-06-30   3   342    오금   5  ...   341

       16시인원  17시인원  18시인원  19시인원  20시인원  21시인원  22시인원  23시인원  24시인원
120      184    160    139    128    123     75     44     20      0
121      216    224    203    168    167    135    119     76      0
122      939    774    631    449    449    354    280     49      1
123      866    757    722    611    526    492    382    339     37
124     1393   1162    953    752    714    594    456    157      4
...      ...    ...    ...    ...    ...    ...    ...    ...    ...
98240    637    743   1124    737    454    308    444    269    116
98241    439    784    883    313    227    181    117     64     10
98242    326    654    837    752    366    311    350    198     92
98243    351    462    555    221    159    144    106     39      7
98244    387    626    863    582    391    299    465    295    124

[12025 rows x 31 columns]
Index(['년도', '월', '주차', '공휴일', '주중주말', '수송일자', '호선', '역사코드', '역이름', '요일',
       '승하차구분', '06시인원', '06시인원', '07시인원', '08시인원', '09시인원', '10시인원', '11시인원',
       '12시인원', '13시인원', '14시인원', '15시인원', '16시인원', '17시인원', '18시인원', '19시인원',
       '20시인원', '21시인원', '22시인원', '23시인원', '24시인원'],
      dtype='object')
         년도  월  주차  공휴일 주중주말        수송일자  호선  역사코드    역이름  요일  ... 15시인원  \
186    2022  1  52    0  DAY  2023-01-01   4   409    당고개   0  ...   366
187    2022  1  52    0  DAY  2023-01-01   4   409    당고개   0  ...   280
188    2022  1  52    0  DAY  2023-01-01   4   410     상계   0  ...   646
189    2022  1  52    0  DAY  2023-01-01   4   410     상계   0  ...   611
190    2022  1  52    0  DAY  2023-01-01   4   411     노원   0  ...   721
...     ... ..  ..  ...  ...         ...  ..   ...    ...  ..  ...   ...
98292  2023  6  26    1  SAT  2023-06-30   4   432  총신대입구   5  ...  1250
98293  2023  6  26    1  SAT  2023-06-30   4   433     사당   5  ...  1274
98294  2023  6  26    1  SAT  2023-06-30   4   433     사당   5  ...  1161
98295  2023  6  26    1  SAT  2023-06-30   4   434    남태령   5  ...    76
98296  2023  6  26    1  SAT  2023-06-30   4   434    남태령   5  ...    54

       16시인원  17시인원  18시인원  19시인원  20시인원  21시인원  22시인원  23시인원  24시인원
186      422    312    258    169    144    123     80     12      0
187      302    353    310    309    235    245    268    188     22
188      685    604    547    396    298    259    180     69      0
189      645    668    587    546    459    565    443    359      0
190      705    722    625    591    608    589    560    234      0
...      ...    ...    ...    ...    ...    ...    ...    ...    ...
98292   1708   2227   3451   2122   1145    899    909    552    248
98293   1567   1842   2054   1321   1161   1409   1647   1011    135
98294   1713   2804   4140   2732   1297   1219   1249    959    336
98295    194    238    188     63     24     33     23      7      1
98296     57     64     62     70     53     41     29     22      9

[9412 rows x 31 columns]
Index(['년도', '월', '주차', '공휴일', '주중주말', '수송일자', '호선', '역사코드', '역이름', '요일',
       '승하차구분', '06시인원', '06시인원', '07시인원', '08시인원', '09시인원', '10시인원', '11시인원',
       '12시인원', '13시인원', '14시인원', '15시인원', '16시인원', '17시인원', '18시인원', '19시인원',
       '20시인원', '21시인원', '22시인원', '23시인원', '24시인원'],
      dtype='object')
         년도  월  주차  공휴일 주중주말        수송일자  호선  역사코드    역이름  요일  ... 15시인원  \
238    2022  1  52    0  DAY  2023-01-01   5  2511     방화   0  ...   261
239    2022  1  52    0  DAY  2023-01-01   5  2511     방화   0  ...   213
240    2022  1  52    0  DAY  2023-01-01   5  2512    개화산   0  ...   181
241    2022  1  52    0  DAY  2023-01-01   5  2512    개화산   0  ...   151
242    2022  1  52    0  DAY  2023-01-01   5  2513   김포공항   0  ...   494
...     ... ..  ..  ...  ...         ...  ..   ...    ...  ..  ...   ...
98404  2023  6  26    1  SAT  2023-06-30   5  2564   하남풍산   5  ...   211
98405  2023  6  26    1  SAT  2023-06-30   5  2565   하남시청   5  ...   388
98406  2023  6  26    1  SAT  2023-06-30   5  2565   하남시청   5  ...   450
98407  2023  6  26    1  SAT  2023-06-30   5  2566  하남검단산   5  ...   395
98408  2023  6  26    1  SAT  2023-06-30   5  2566  하남검단산   5  ...   424

       16시인원  17시인원  18시인원  19시인원  20시인원  21시인원  22시인원  23시인원  24시인원
238      246    211    143     80     94     45     39      9      1
239      264    279    268    177    195    157    214    122     24
240      149    148    143     84     65     52     43     15      1
241      194    179    147    174    142    148    140     95     22
242      599    627    559    465    442    446    433    166      0
...      ...    ...    ...    ...    ...    ...    ...    ...    ...
98404    275    331    458    407    213    186    205    140     69
98405    486    548    610    307    258    180    149     47     25
98406    505    655    921    910    428    460    423    341    183
98407    467    528    503    318    211    196    146     51      5
98408    348    498    665    619    335    341    279    319    180

[20272 rows x 31 columns]
Index(['년도', '월', '주차', '공휴일', '주중주말', '수송일자', '호선', '역사코드', '역이름', '요일',
       '승하차구분', '06시인원', '06시인원', '07시인원', '08시인원', '09시인원', '10시인원', '11시인원',
       '12시인원', '13시인원', '14시인원', '15시인원', '16시인원', '17시인원', '18시인원', '19시인원',
       '20시인원', '21시인원', '22시인원', '23시인원', '24시인원'],
      dtype='object')
         년도  월  주차  공휴일 주중주말        수송일자  호선  역사코드   역이름  요일  ... 15시인원  \
350    2022  1  52    0  DAY  2023-01-01   6  2611    응암   0  ...   564
351    2022  1  52    0  DAY  2023-01-01   6  2611    응암   0  ...   603
352    2022  1  52    0  DAY  2023-01-01   6  2612    역촌   0  ...   126
353    2022  1  52    0  DAY  2023-01-01   6  2612    역촌   0  ...   145
354    2022  1  52    0  DAY  2023-01-01   6  2613    불광   0  ...   275
...     ... ..  ..  ...  ...         ...  ..   ...   ...  ..  ...   ...
98478  2023  6  26    1  SAT  2023-06-30   6  2646  태릉입구   5  ...   344
98479  2023  6  26    1  SAT  2023-06-30   6  2647   화랑대   5  ...   521
98480  2023  6  26    1  SAT  2023-06-30   6  2647   화랑대   5  ...   447
98481  2023  6  26    1  SAT  2023-06-30   6  2648   봉화산   5  ...   352
98482  2023  6  26    1  SAT  2023-06-30   6  2648   봉화산   5  ...   482

       16시인원  17시인원  18시인원  19시인원  20시인원  21시인원  22시인원  23시인원  24시인원
350      606    516    381    317    292    191    149     62      6
351      657    732    686    667    575    576    545    306     66
352      145    122     91     62     47     52     41     10      0
353      179    166    144    149    128    163    126     86      0
354      287    281    194    135    149    113     54     31      1
...      ...    ...    ...    ...    ...    ...    ...    ...    ...
98478    451    588    980    761    409    387    365    351    219
98479    533    647    552    301    179    153    132     49     18
98480    538    820   1394   1188    629    579    554    490    264
98481    440    523    497    271    164    163    118     62     16
98482    549    781   1327   1124    616    485    601    349    246

[13442 rows x 31 columns]
Index(['년도', '월', '주차', '공휴일', '주중주말', '수송일자', '호선', '역사코드', '역이름', '요일',
       '승하차구분', '06시인원', '06시인원', '07시인원', '08시인원', '09시인원', '10시인원', '11시인원',
       '12시인원', '13시인원', '14시인원', '15시인원', '16시인원', '17시인원', '18시인원', '19시인원',
       '20시인원', '21시인원', '22시인원', '23시인원', '24시인원'],
      dtype='object')
         년도  월  주차  공휴일 주중주말        수송일자  호선  역사코드    역이름  요일  ... 15시인원  \
424    2022  1  52    0  DAY  2023-01-01   7  2711     장암   0  ...    86
425    2022  1  52    0  DAY  2023-01-01   7  2711     장암   0  ...    47
426    2022  1  52    0  DAY  2023-01-01   7  2712    도봉산   0  ...   470
427    2022  1  52    0  DAY  2023-01-01   7  2712    도봉산   0  ...   286
428    2022  1  52    0  DAY  2023-01-01   7  2713    수락산   0  ...   540
...     ... ..  ..  ...  ...         ...  ..   ...    ...  ..  ...   ...
98562  2023  6  26    1  SAT  2023-06-30   7  2750  광명사거리   5  ...  1246
98563  2023  6  26    1  SAT  2023-06-30   7  2751     천왕   5  ...   484
98564  2023  6  26    1  SAT  2023-06-30   7  2751     천왕   5  ...   636
98565  2023  6  26    1  SAT  2023-06-30   7  2752     온수   5  ...   405
98566  2023  6  26    1  SAT  2023-06-30   7  2752     온수   5  ...   370

       16시인원  17시인원  18시인원  19시인원  20시인원  21시인원  22시인원  23시인원  24시인원
424       75     99     74     49     32     15     10      2      0
425       32     30     27     21     26     11     16      4      2
426      372    314    236    166    118     69     63     21      0
427      327    272    306    263    249    192    228    167     31
428      547    440    362    284    209    161    106     44      1
...      ...    ...    ...    ...    ...    ...    ...    ...    ...
98562   1519   2017   3320   2346   1187   1101    934    703    281
98563    610    620    607    340    269    185    133     72     17
98564    730   1103   1987   1420    806    615    631    467    212
98565    501    529    599    258    176    197    131     87     22
98566    558    864   1600   1277    681    577    555    383    316

[15216 rows x 31 columns]
Index(['년도', '월', '주차', '공휴일', '주중주말', '수송일자', '호선', '역사코드', '역이름', '요일',
       '승하차구분', '06시인원', '06시인원', '07시인원', '08시인원', '09시인원', '10시인원', '11시인원',
       '12시인원', '13시인원', '14시인원', '15시인원', '16시인원', '17시인원', '18시인원', '19시인원',
       '20시인원', '21시인원', '22시인원', '23시인원', '24시인원'],
      dtype='object')
         년도  월  주차  공휴일 주중주말        수송일자  호선  역사코드   역이름  요일  ... 15시인원  \
508    2022  1  52    0  DAY  2023-01-01   8  2811    암사   0  ...   527
509    2022  1  52    0  DAY  2023-01-01   8  2811    암사   0  ...   619
510    2022  1  52    0  DAY  2023-01-01   8  2812    천호   0  ...   521
511    2022  1  52    0  DAY  2023-01-01   8  2812    천호   0  ...   637
512    2022  1  52    0  DAY  2023-01-01   8  2813  강동구청   0  ...   286
...     ... ..  ..  ...  ...         ...  ..   ...   ...  ..  ...   ...
98598  2023  6  26    1  SAT  2023-06-30   8  2826    수진   5  ...   290
98599  2023  6  26    1  SAT  2023-06-30   8  2827    모란   5  ...   320
98600  2023  6  26    1  SAT  2023-06-30   8  2827    모란   5  ...   250
98601  2023  6  26    1  SAT  2023-06-30   8  2828   남위례   5  ...   350
98602  2023  6  26    1  SAT  2023-06-30   8  2828   남위례   5  ...   332

       16시인원  17시인원  18시인원  19시인원  20시인원  21시인원  22시인원  23시인원  24시인원
508      468    476    347    281    226    184    127     43      0
509      637    644    591    580    488    471    484    299     31
510      510    466    461    373    321    248    243     84      0
511      675    753    664    569    488    499    363    239     26
512      279    281    217    172    206    123     64     38      0
...      ...    ...    ...    ...    ...    ...    ...    ...    ...
98598    357    470    566    470    316    276    242    232    102
98599    466    410    467    271    188    180    138    138     59
98600    265    289    505    273    182    161    163     95    131
98601    591    776    832    357    266    286    210    115     38
98602    451    630    978    827    339    362    380    291    154

[6516 rows x 31 columns]
Index(['년도', '월', '주차', '공휴일', '주중주말', '수송일자', '호선', '역사코드', '역이름', '요일',
       '승하차구분', '06시인원', '06시인원', '07시인원', '08시인원', '09시인원', '10시인원', '11시인원',
       '12시인원', '13시인원', '14시인원', '15시인원', '16시인원', '17시인원', '18시인원', '19시인원',
       '20시인원', '21시인원', '22시인원', '23시인원', '24시인원'],
      dtype='object')
          년도   월  주차  공휴일 주중주말        수송일자  호선  역사코드  역이름  요일  ... 15시인원  \
0       2022   1  52    0  DAY  2023-01-01   1   150  서울역   0  ...  2655
1       2022   1  52    0  DAY  2023-01-01   1   150  서울역   0  ...  2282
2       2022   1  52    0  DAY  2023-01-01   1   151   시청   0  ...   843
3       2022   1  52    0  DAY  2023-01-01   1   151   시청   0  ...   602
4       2022   1  52    0  DAY  2023-01-01   1   152   종각   0  ...  1145
...      ...  ..  ..  ...  ...         ...  ..   ...  ...  ..  ...   ...
164847  2023  10  44    1  DAY  2023-10-31   1   157  제기동   2  ...  1347
164848  2023  10  44    1  DAY  2023-10-31   1   158  청량리   2  ...  1748
164849  2023  10  44    1  DAY  2023-10-31   1   158  청량리   2  ...  1688
164850  2023  10  44    1  DAY  2023-10-31   1   159  동묘앞   2  ...  1041
164851  2023  10  44    1  DAY  2023-10-31   1   159  동묘앞   2  ...   833

        16시인원  17시인원  18시인원  19시인원  20시인원  21시인원  22시인원  23시인원  24시인원
0        2509   2696   2549   2462   2177   2190   1808    734      7
1        2295   2526   1930   1897   1487    991    609    280     46
2         895    959    985    670    630    515    330    146      0
3         575    533    456    285    267    246    154     79     18
4        1402   1223   1272    911    913    906    602    232      3
...       ...    ...    ...    ...    ...    ...    ...    ...    ...
164847   1156    910   1069    707    463    410    320    234     60
164848   2009   1900   1581    852    713    567    336    122     16
164849   1487   1634   2315   1286    827    741    643    346    145
164850   1063   1072    599    269    208    173    107     36      7
164851    624    538    407    263    228    220    213    153     71

[6080 rows x 31 columns]
Index(['년도', '월', '주차', '공휴일', '주중주말', '수송일자', '호선', '역사코드', '역이름', '요일',
       '승하차구분', '06시인원', '06시인원', '07시인원', '08시인원', '09시인원', '10시인원', '11시인원',
       '12시인원', '13시인원', '14시인원', '15시인원', '16시인원', '17시인원', '18시인원', '19시인원',
       '20시인원', '21시인원', '22시인원', '23시인원', '24시인원'],
      dtype='object')
          년도   월  주차  공휴일 주중주말        수송일자  호선  역사코드    역이름  요일  ... 15시인원  \
20      2022   1  52    0  DAY  2023-01-01   2   201     시청   0  ...   601
21      2022   1  52    0  DAY  2023-01-01   2   201     시청   0  ...   450
22      2022   1  52    0  DAY  2023-01-01   2   202  을지로입구   0  ...  1372
23      2022   1  52    0  DAY  2023-01-01   2   202  을지로입구   0  ...  1145
24      2022   1  52    0  DAY  2023-01-01   2   203  을지로3가   0  ...   774
...      ...  ..  ..  ...  ...         ...  ..   ...    ...  ..  ...   ...
164947  2023  10  44    1  DAY  2023-10-31   2   248   양천구청   2  ...   432
164948  2023  10  44    1  DAY  2023-10-31   2   249  신정네거리   2  ...   398
164949  2023  10  44    1  DAY  2023-10-31   2   249  신정네거리   2  ...   617
164950  2023  10  44    1  DAY  2023-10-31   2   250     용두   2  ...   143
164951  2023  10  44    1  DAY  2023-10-31   2   250     용두   2  ...   168

        16시인원  17시인원  18시인원  19시인원  20시인원  21시인원  22시인원  23시인원  24시인원
20        627    761    801    581    507    503    304    145      1
21        371    354    308    227    232    237    208     99     13
22       1556   1687   1901   1347   1333   1162   1029    346      7
23       1319   1289   1082    874    732    612    414    200    181
24        847    748    714    554    508    423    366    202      0
...       ...    ...    ...    ...    ...    ...    ...    ...    ...
164947    533    849   1372   1091    619    457    418    306    102
164948    415    434    431    248    174    160    119     52      6
164949    900   1270   2063   1423    820    821    562    351    139
164950    197    168    196    107     59     53     22      8      7

In [ ]:

## 배차 시간대 칼럼 이름 ~배차로 바꾸기 

for key in mlTable_dict.keys():
    for line in mlTable_dict[key].keys():
        table = mlTable_dict[key][line]
        colnamelist = table.columns
        배차StartIndex = Service.indexFind(colnamelist=colnamelist.tolist(),search_target_word='05')[0]
        배차FinalIndex = Service.indexFind(colnamelist=colnamelist.tolist(),search_target_word='24')[0]
        for colname in colnamelist[배차StartIndex:배차FinalIndex+1]:
            # print(f'{colname[:2]}시인원')
            table.rename({colname:f'{colname[:2]}배차'}, inplace=True, axis=1)
        mlTable_dict[key][line]=table

mlTable_dict.keys()
# mlTable_dict['subway23_0']['subway23_0_1'].columns

dict_keys(['subway23_0', 'subway23_1', 'subway23_2', 'subway22'])

In [ ]:
# 칼럼 순서이동 및 쓸데없는 칼럼 버리기 
move_target_colname_list =[ '년도', '월', '주차', '공휴일', '수송일자', '요일', '승하차구분']

# for line in mlTable_dict['subway23_0']['subway23_0_1']:
    
for key in mlTable_dict.keys():
    for line in mlTable_dict[key].keys():
        table = mlTable_dict[key][line]
        table.drop('주중주말', axis=1, inplace=True)
        table.drop('수송일자', axis=1, inplace=True)
        table.drop('년도', axis=1, inplace=True)
        mlTable_dict[key][line]=table


# mlTable_dict['subway23_0']['subway23_0_1'].columns


input_column=['월', '주차', '공휴일', '요일', '역사코드', '주중', '주말',
    'latitude', 'longitude', '05배차', '06배차', '07배차', '08배차', '09배차', '10배차',
    '11배차', '12배차', '13배차', '14배차', '15배차', '16배차', '17배차', '18배차', '19배차',
    '20배차', '21배차', '22배차', '23배차', '24배차']
target_column=['05시인원', '06시인원', '07시인원',
'08시인원', '09시인원', '10시인원', '11시인원', '12시인원', '13시인원', '14시인원', '15시인원',
'16시인원', '17시인원', '18시인원', '19시인원', '20시인원', '21시인원', '22시인원', '23시인원',
'24시인원']

KeyError: "['주중주말'] not found in axis"